name: Build Dockerfile and push

on:
  push:
    tag:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push app image
        uses: docker/build-push-action@v4
        with:
          context: 1.\ Containerization/Le\ Van\ Chien/app/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app:${{ github.ref }}

      - name: Build and push web image
        uses: docker/build-push-action@v4
        with:
          context: 1.\ Containerization/Le\ Van\ Chien/nginx/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web:${{ github.refname }}
